### ISSUE TITLE
apk crash

### ISSUE THREAD

**Issue by kiyse** [djh123/doc_Detection#1]
复制工程到AS,安装上apk后，闪退，报错com.taobao.android.mnndemo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 14060 (MNNNet), pid 14026 (android.mnndemo)

**Comment by djh123** [comment]
是否解决了呢？很久没有看github了。没有的话可以加我qq:1318776407
