### ISSUE TITLE
自己训练的模型转MNN失败的问题

### ISSUE THREAD

**Issue by tunmx** [djh123/doc_Detection#2]
您好，我自己基于tf_doc_localisation这个项目训练了一个模型，在转换成MNN模型时遇到以下问题

```
libc++abi.dylib: terminating with uncaught exception of type Error: [00:42:03] /Users/yutianhang/Desktop/AliNN/AliNNPrivate/tools/converter/source/common/writeFb.cpp:108: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: Tensorflow::FusedBatchNormV3 | 
Abort trap: 6

```

我大概知道是因为模型里面的FusedBatchNorm的is_training没有设置成false的问题，但是我不知道怎么在导出pb时去设置成false，如果直接读取graph去设置成false，pb模型无法导出，但是原作者没有给出导出pb模型的方式，作者给出的
frozen_model.pb我查看了网络结构，is_training这个参数确实是false，请问您是否有重新训练模型，如果有的话，是怎样导出MNN能支持的pb模型的呢

**Comment by djh123** [comment]
我是,is_training 重新训练了一轮

**Comment by JaosonMa** [comment]
> 我是,is_training 重新训练了一轮

请问，具体如何重新训练才能导出is_training=false的模型

**Comment by JaosonMa** [comment]
> 您好，我自己基于tf_doc_localisation这个项目训练了一个模型，在转换成MNN模型时遇到以下问题
> 
> ```
> libc++abi.dylib: terminating with uncaught exception of type Error: [00:42:03] /Users/yutianhang/Desktop/AliNN/AliNNPrivate/tools/converter/source/common/writeFb.cpp:108: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: Tensorflow::FusedBatchNormV3 | 
> Abort trap: 6
> ```
> 
> 我大概知道是因为模型里面的FusedBatchNorm的is_training没有设置成false的问题，但是我不知道怎么在导出pb时去设置成false，如果直接读取graph去设置成false，pb模型无法导出，但是原作者没有给出导出pb模型的方式，作者给出的 frozen_model.pb我查看了网络结构，is_training这个参数确实是false，请问您是否有重新训练模型，如果有的话，是怎样导出MNN能支持的pb模型的呢

@tunmx 请问你解决这个问题吗？如何才能导出is_training=false的模型

**Comment by tunmx** [comment]
你好，后面我放弃了用tf那个项目，自己使用torch训了

**Comment by JaosonMa** [comment]
> 你好，后面我放弃了用tf那个项目，自己使用torch训了

好的，请问您的项目可以开源吗？可以加您联系方式吗？

**Comment by tunmx** [comment]
你好，当时做的这个任务已经移交给同事， 由于是公司的项目不太方便开源哈
